// Package e2e runs the ported generator against the fixtures in
// test/valid-data, comparing generated schemas with the checked-in
// schema.json files. The fixture list lives in test/fixtures-manifest.json
// (generated by tools/extract_fixtures).
package e2e

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"reflect"
	"runtime"
	"sort"
	"strings"
	"testing"

	"github.com/vega/ts-json-schema-generator/internal/config"
	"github.com/vega/ts-json-schema-generator/internal/factory"
)

type manifestEntry struct {
	Name       string         `json:"name"`
	Types      []string       `json:"types,omitempty"`
	Config     map[string]any `json:"config,omitempty"`
	MainTsOnly bool           `json:"mainTsOnly,omitempty"`
	Skip       string         `json:"skip,omitempty"`
}

func repoRoot(t *testing.T) string {
	t.Helper()
	_, file, _, ok := runtime.Caller(0)
	if !ok {
		t.Fatal("cannot determine caller file")
	}
	return filepath.Dir(filepath.Dir(filepath.Dir(file)))
}

// wiringPending reports whether the parser/formatter factories are still
// integration stubs. It probes CreateFormatter, which panics with a known
// message until the full chain is wired; once the stubs are removed this
// returns false and the fixtures run for real.
func wiringPending() (pending bool) {
	defer func() {
		if r := recover(); r != nil {
			if fmt.Sprintf("%v", r) == "wiring completed at integration" {
				pending = true
				return
			}
			panic(r)
		}
	}()
	factory.CreateFormatter(config.Default())
	return false
}

func TestValidData(t *testing.T) {
	root := repoRoot(t)

	data, err := os.ReadFile(filepath.Join(root, "test", "fixtures-manifest.json"))
	if err != nil {
		t.Fatalf("cannot read fixtures manifest (run `go run ./tools/extract_fixtures`): %v", err)
	}
	var manifest []manifestEntry
	if err := json.Unmarshal(data, &manifest); err != nil {
		t.Fatalf("cannot parse fixtures manifest: %v", err)
	}

	if wiringPending() {
		t.Skip("wiring pending: factory.CreateParser/CreateFormatter are stubs")
	}

	seen := map[string]int{}
	for _, entry := range manifest {
		seen[entry.Name]++
		testName := entry.Name
		if seen[entry.Name] > 1 {
			testName = fmt.Sprintf("%s#%d", entry.Name, seen[entry.Name])
		}
		t.Run(testName, func(t *testing.T) {
			if entry.Skip != "" {
				t.Skipf("skipped by manifest: %s", entry.Skip)
			}
			runFixture(t, root, entry)
		})
	}
}

func runFixture(t *testing.T, root string, entry manifestEntry) {
	t.Helper()

	cfg, err := fixtureConfig(root, entry)
	if err != nil {
		t.Fatal(err)
	}

	generator, release, err := factory.CreateGenerator(cfg)
	if err != nil {
		t.Fatalf("CreateGenerator: %v", err)
	}
	defer release()

	actualSchema, err := generator.CreateSchema(entry.Types)
	if err != nil {
		t.Fatalf("CreateSchema: %v", err)
	}

	actualJSON, err := json.Marshal(actualSchema)
	if err != nil {
		t.Fatalf("marshal generated schema: %v", err)
	}
	var actual any
	if err := json.Unmarshal(actualJSON, &actual); err != nil {
		t.Fatalf("round-trip generated schema: %v", err)
	}

	expectedJSON, err := os.ReadFile(filepath.Join(root, "test", "valid-data", entry.Name, "schema.json"))
	if err != nil {
		t.Fatalf("read expected schema: %v", err)
	}
	var expected any
	if err := json.Unmarshal(expectedJSON, &expected); err != nil {
		t.Fatalf("parse expected schema: %v", err)
	}

	if !reflect.DeepEqual(actual, expected) {
		var diffs []string
		diffJSON("$", expected, actual, &diffs)
		if len(diffs) > 20 {
			diffs = append(diffs[:20], fmt.Sprintf("... and %d more differences", len(diffs)-20))
		}
		t.Errorf("schema mismatch:\n%s", strings.Join(diffs, "\n"))
	}
}

func fixtureConfig(root string, entry manifestEntry) (*config.Config, error) {
	cfg := config.Default()
	// Type checking the fixtures is slow and is covered upstream; skip it.
	cfg.SkipTypeCheck = true
	cfg.Types = entry.Types

	glob := "*.ts"
	if entry.MainTsOnly {
		glob = "main.ts"
	}
	cfg.Path = filepath.Join(root, "test", "valid-data", entry.Name, glob)

	for key, value := range entry.Config {
		switch key {
		case "jsDoc":
			cfg.JSDoc = config.JSDocMode(value.(string))
		case "expose":
			cfg.Expose = config.Expose(value.(string))
		case "schemaId":
			cfg.SchemaID = value.(string)
		case "discriminatorType":
			cfg.DiscriminatorType = config.DiscriminatorType(value.(string))
		case "functions":
			cfg.Functions = config.FunctionOptions(value.(string))
		case "tsconfig":
			tsconfig := value.(string)
			if !filepath.IsAbs(tsconfig) {
				tsconfig = filepath.Join(root, tsconfig)
			}
			cfg.Tsconfig = tsconfig
		case "topRef":
			cfg.TopRef = value.(bool)
		case "additionalProperties":
			cfg.AdditionalProperties = value.(bool)
		case "sortProps":
			cfg.SortProps = value.(bool)
		case "encodeRefs":
			cfg.EncodeRefs = value.(bool)
		case "markdownDescription":
			cfg.MarkdownDescription = value.(bool)
		case "fullDescription":
			cfg.FullDescription = value.(bool)
		case "minify":
			cfg.Minify = value.(bool)
		case "strictTuples":
			cfg.StrictTuples = value.(bool)
		case "skipTypeCheck":
			cfg.SkipTypeCheck = value.(bool)
		case "extraTags":
			for _, item := range value.([]any) {
				cfg.ExtraTags = append(cfg.ExtraTags, item.(string))
			}
		default:
			return nil, fmt.Errorf("unsupported config key %q in manifest", key)
		}
	}
	return cfg, nil
}

// diffJSON records human-readable differences between two decoded JSON
// values.
func diffJSON(path string, expected, actual any, diffs *[]string) {
	if reflect.DeepEqual(expected, actual) {
		return
	}
	switch exp := expected.(type) {
	case map[string]any:
		act, ok := actual.(map[string]any)
		if !ok {
			*diffs = append(*diffs, fmt.Sprintf("%s: expected object, got %s", path, describeJSON(actual)))
			return
		}
		keys := map[string]bool{}
		for key := range exp {
			keys[key] = true
		}
		for key := range act {
			keys[key] = true
		}
		sorted := make([]string, 0, len(keys))
		for key := range keys {
			sorted = append(sorted, key)
		}
		sort.Strings(sorted)
		for _, key := range sorted {
			expValue, expOK := exp[key]
			actValue, actOK := act[key]
			childPath := path + "." + key
			switch {
			case !expOK:
				*diffs = append(*diffs, fmt.Sprintf("%s: unexpected key (got %s)", childPath, describeJSON(actValue)))
			case !actOK:
				*diffs = append(*diffs, fmt.Sprintf("%s: missing key (want %s)", childPath, describeJSON(expValue)))
			default:
				diffJSON(childPath, expValue, actValue, diffs)
			}
		}
	case []any:
		act, ok := actual.([]any)
		if !ok {
			*diffs = append(*diffs, fmt.Sprintf("%s: expected array, got %s", path, describeJSON(actual)))
			return
		}
		if len(exp) != len(act) {
			*diffs = append(*diffs, fmt.Sprintf("%s: array length mismatch: want %d, got %d", path, len(exp), len(act)))
		}
		for i := 0; i < len(exp) && i < len(act); i++ {
			diffJSON(fmt.Sprintf("%s[%d]", path, i), exp[i], act[i], diffs)
		}
	default:
		*diffs = append(*diffs, fmt.Sprintf("%s: want %s, got %s", path, describeJSON(expected), describeJSON(actual)))
	}
}

func describeJSON(value any) string {
	data, err := json.Marshal(value)
	if err != nil {
		return fmt.Sprintf("%v", value)
	}
	if len(data) > 120 {
		return string(data[:120]) + "..."
	}
	return string(data)
}
