name: Publish Auto

on:
  push:
    branches-ignore:
      # No canary deploys for branches opened by dependabot
      - "dependabot/**"

permissions:
  contents: write
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci') }}

    name: Make a release and publish to NPM
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v6
        with:
          cache: "npm"
          node-version: 22

      - name: Install Node dependencies
        run: npm ci

      - name: Update NPM
        run: npm i -g npm@latest

      - name: Create release
        run: npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
