name: Test

on:
  push:
    branches:
      - next
  pull_request:
    branches:
      - next

jobs:
  build:
    name: Build and Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: "npm"

      - name: Install Node dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build

  test:
    name: Test (Shard ${{ matrix.shard }}/6)
    needs: build

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        shard: [1, 2, 3, 4, 5, 6]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: "npm"

      - name: Install Node dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Test coverage
        run: npm run test:coverage -- --test-shard=${{ matrix.shard }}/6

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
